version: "3.1"

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=duct-init-development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-test:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=duct-init-test
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "postgres://postgres:password@db:5432/duct-init-development?sslmode=disable",
        "up"
      ]
    links:
      - db
  migrate-test:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "postgres://postgres:password@db-test:5432/duct-init-test?sslmode=disable",
        "up"
      ]
    links:
      - db-test

volumes:
  postgres-data:
    driver: local
