#!/bin/bash
set -Ceux

# コマンド実行時の第2引数以下をARGに格納
ARGS=${@:2}

case ${1} in
"setup") ##
[ -z $(which clojure) ] && brew install clojure/tools/clojure
[ -z $(which lein) ] && brew install leiningen
[ -z $(which migrate) ] && brew install golang-migrate
lein duct setup
;;
"up") ##
docker compose up
;;
"repl") ##
lein repl
;;
"migrate") ##
[ -z $(which migrate) ] && brew install golang-migrate
migrate -source file://./db/migrations -database postgresql://postgres:password@localhost:5433/duct-init-development?sslmode=disable up
# docker compose run -T db psql postgresql://postgres:password@db:5432/duct-init-development?sslmode=disable < db/seeds/*.sql
migrate -source file://./db/migrations -database postgresql://postgres:password@localhost:5434/duct-init-test?sslmode=disable up
;;
"migrate-down") ##
migrate -source file://./db/migrations -database postgresql://postgres:password@localhost:5433/duct-init-development?sslmode=disable down
migrate -source file://./db/migrations -database postgresql://postgres:password@localhost:5434/duct-init-test?sslmode=disable down
;;
"psql") ##
docker compose run -T db psql postgresql://postgres:password@db:5432/duct-init-development?sslmode=disable
;;
"test") ##
lein eftest $ARGS
;;
"help" | *)
(
echo "HELP"
echo "  COMMAND ) DESCRIPTION ) REQUIRE ) ARGS"
\grep -E "\)\ *\##" ${0}
) | column -t -s "\)"
;;
esac
