#!/bin/bash
set -Ceux

# コマンド実行時の第2引数以下をARGに格納
ARGS=${@:2}

case ${1} in
"setup") ##
[ -z $(which clojure) ] && brew install clojure/tools/clojure
[ -z $(which lein) ] && brew install leiningen
lein duct setup
docker compose up db db-test -d
sleep 5
docker compose up migrate migrate-test
docker compose up
;;
"up") ##
docker compose up
;;
"repl") ##
lein repl
;;
"seed") ##
docker compose exec -T db psql postgresql://postgres:password@db:5432/crane-server-development?sslmode=disable < db/seeds/*.sql
;;
"psql") ##
docker compose exec -T db psql postgresql://postgres:password@db:5432/crane-server-development?sslmode=disable
;;
"test") ##
lein eftest $ARGS && ./cleanup-testdb
;;
"help" | *)
(
echo "HELP"
echo "  COMMAND ) DESCRIPTION ) REQUIRE ) ARGS"
\grep -E "\)\ *\##" ${0}
) | column -t -s "\)"
;;
esac
